### ISSUE TITLE
company-quickhelp is not available in this emacs version or frame

### ISSUE THREAD

**Issue by mhcerri** [auto-complete/popup-el#115]
Hi,

I'm getting the following error when trying to use it on a terminal:

```
Error running timer `company-quickhelp--show': (error "company-quickhelp is not available in this emacs version or frame") 
```
It works fine with the GTK version. I'm using emacs 24.5.1.

**Comment by articuluxe** [comment]
You are reporting this on the wrong repo, it should be reported at:

https://github.com/expez/company-quickhelp

Also, note that company-quickhelp relies on pos-tip, due to supposed glitches in popup; it’s authors conveniently ignore that pos-tip doesn’t work in the terminal. So I think what you trying to do will not work.

**Comment by mhcerri** [comment]
I totally mixed up the projects. Thank you.
